-- 코드를 입력하세요

  SELECT R.FOOD_TYPE
       , R.REST_ID
       , R.REST_NAME
       , R2.FAVORITES
    FROM REST_INFO R, 
         (SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES FROM REST_INFO GROUP BY FOOD_TYPE) R2
   WHERE R.FOOD_TYPE = R2.FOOD_TYPE
     AND R.FAVORITES = R2.FAVORITES
ORDER BY R.FOOD_TYPE DESC
   
   