-- 코드를 입력하세요

  SELECT I.ANIMAL_ID
       , I.ANIMAL_TYPE
       , I.NAME
    FROM ANIMAL_INS I
       , ANIMAL_OUTS O
   WHERE O.ANIMAL_ID = I.ANIMAL_ID
     AND I.SEX_UPON_INTAKE LIKE 'Intact%'
     AND O.SEX_UPON_OUTCOME NOT LIKE 'Intact%'
ORDER BY I.ANIMAL_ID