

-- 난 CONNECT BY LEVEL 문법 자체를 처음본다 와우 
-- LEVEL은 기본이 1이라 0부터 시작하려면 -1을 해주면 됨.
  SELECT A.HOUR
       , COUNT(B.TIME)
    FROM (SELECT LEVEL-1 AS HOUR FROM DUAL CONNECT BY LEVEL <25) A 
         LEFT OUTER JOIN
         (SELECT TO_CHAR(DATETIME,'HH24') AS TIME FROM ANIMAL_OUTS) B
      ON A.HOUR = B.TIME
GROUP BY A.HOUR
ORDER BY A.HOUR