-- 코드를 입력하세요

  SELECT FLAVOR
    FROM (
  SELECT H.FLAVOR,
         H.TOTAL_ORDER+J.TOTAL_ORDER
    FROM FIRST_HALF H, 
         (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER FROM JULY GROUP BY FLAVOR) J
   WHERE H.FLAVOR = J.FLAVOR
ORDER BY 2 DESC )
   WHERE ROWNUM <= 3 

--SELECT * FROM FIRST_HALF
--SELECT * FROM JULY

