-- 코드를 입력하세요
SELECT M.MEMBER_NAME, R.REVIEW_TEXT, TO_CHAR(R.REVIEW_DATE, 'YYYY-MM-DD')
FROM MEMBER_PROFILE M, REST_REVIEW R 
WHERE M.MEMBER_ID = R.MEMBER_ID 
AND R.MEMBER_ID IN ( SELECT MEMBER_ID FROM REST_REVIEW GROUP BY MEMBER_ID 
HAVING COUNT(*) >= (SELECT MAX(REVIEW_COUNT) 
FROM (SELECT MEMBER_ID, COUNT(*) AS REVIEW_COUNT FROM REST_REVIEW GROUP BY MEMBER_ID)) )
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT;
