-- 코드를 입력하세요

SELECT HOUR, COUNT(HOUR)
FROM
(
SELECT EXTRACT(HOUR FROM CAST(DATETIME AS TIMESTAMP)) AS HOUR
FROM ANIMAL_OUTS 
WHERE EXTRACT(HOUR FROM CAST(DATETIME AS TIMESTAMP)) >= 9
AND EXTRACT(HOUR FROM CAST(DATETIME AS TIMESTAMP)) < 20
)
GROUP BY HOUR
ORDER BY HOUR