-- 코드를 입력하세요
SELECT MEMBER_ID, MEMBER_NAME, GENDER, to_char(DATE_OF_BIRTH, 'YYYY-MM-DD') as DATE_OF_BIRTH 
FROM MEMBER_PROFILE 
WHERE to_char(DATE_OF_BIRTH, 'mm') = '03'
AND TLNO is not null
AND GENDER = 'W' 
ORDER BY MEMBER_ID;